# Generated by Django 4.1.1 on 2022-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(upload_to='static', verbose_name='Image'),
        ),
    ]
